apiVersion: v1
kind: Pod
metadata:
  name: ${POD_NAME}
  labels:
    app: hailo-worker
    job-id: "${JOB_ID}"
spec:
  hostNetwork: true
  restartPolicy: Never
  containers:
    - name: workload-runner
      image: ${IMAGE_NAME}
      imagePullPolicy: Never

      #command: ["./run_all.sh"]
      command: ["sleep", "infinity"]

      envFrom:
        - configMapRef:
            name: hailort-service-env
      
      env:
        - name: WORKER_JOB_ID
          value: "${JOB_ID}"
        - name: WORKER_INSTANCE_INDEX
          value: "${INSTANCE_INDEX}"

      securityContext:
        privileged: true

      volumeMounts:
        - name: log-output-dir
          mountPath: /app/log_worker
        - name: hailort-socket
          mountPath: /tmp
        - name: hailo-device
          mountPath: /dev/hailo0

  volumes:
    - name: log-output-dir
      hostPath:
        path: /home/hailo/npu-project/log_pod/log_worker
        type: DirectoryOrCreate
    - name: hailort-socket
      hostPath:
        path: /tmp
        type: Directory
    - name: hailo-device
      hostPath:
        path: /dev/hailo0