apiVersion: v1
kind: Pod
metadata:
  name: app-inference-driver
spec:
  hostNetwork: true
  containers:
  - name: app
    image: hailo-app:v1.0
    imagePullPolicy: Never
    command: ["./inference_driver"]  # inference_driver 실행
    securityContext:
      privileged: false
    env:
    - name: HAILORT_SERVICE_ADDRESS
      value: "localhost:50051"